### ISSUE TITLE
Sonar Coverage Problem

### ISSUE THREAD

**Issue by alce65** [isdi-coders-2022/Sirs-Meeseeks-202210-mad#50]
Hola chicos.
Tenéis un error en la configuración de sonar (sonar-project.properties)
Donde pone // debería poner /**/ 
Podéis verlo en los repos de otros equipos.
Como es algo sencillo, corregirlo cuanto antes

**Comment by LuisEnrDiaz** [comment]
Muchas gracias! no sabíamos que problema teníamos, ya lo he corregido
