### ISSUE TITLE
New Code definition in Sonar

### ISSUE THREAD

**Issue by alce65** [isdi-coders-2022/Sirs-Meeseeks-202210-mad#51]
Hola chic@s
Os falta en Sonar la definición de New Code.
Podéis poner la que queráis, pero poner alguna.
Un par de grupos ya lo tienen, así que podéis preguntarles.

**Comment by LuisEnrDiaz** [comment]
Hola Alejandro !
ye tenemos puesto el New Code de sonar.
muchas gracias por la corrección! un saludo.

**Comment by alce65** [comment]
Muy bien.
Cierro el issue
