### ISSUE TITLE
PRs Review

### ISSUE THREAD

**Issue by alce65** [isdi-coders-2022/Sirs-Meeseeks-202210-mad#52]
Estáis aprobando PRs que fallan en el despliegue de Netlify ¿Sabéis por qué? ¿Sois conscientes de que no estarías manteniendo actualizado vuestro despliegue a producción?. O peor aún, quizás ni siquiera funcione.
Echar un vistazo o contarme que es lo que pasa.

Por otro lado, también las aprobáis con fallos en Sonar. ¿Entendéis que no debería ser así? El objetivo de integrar Sonar en nuestro flujo CI/CD es que no llegue a producción software que no cumple con los criterios de calidad que nosotros mismos nos hemos impuesto.

Ya se que vais con prisas, pero esto pasa siempre. Se que lo dejareis bien al final, pero lo siguiente es conseguir tenerlo bien de forma continuada (de ahí el CI/CD)

Mucho ánimo, que ya os queda poco.

**Comment by Xapariciox** [comment]
Gracias por Los consejos. Lo tomaremos en Cuenta en lo que nos queda!

**Comment by Allorentee** [comment]
Gracias Alejandro si que es verdad que vamos un poco con prisas y hay errores que no sabemos solucionar y sino se nos acumulan los cambios y teníamos miedo a que nos generasen muchos conflictos, pero entiendo que no es excusa, intentaremos mejorarlo y actuar de manera profesional

**Comment by alce65** [comment]
Genial.
Os cierro el issue
